name: Secrets Scan

on:
  workflow_call:
    inputs:
      scan-since-commit:
        description: "Commit to scan from (defaults to HEAD~1)"
        required: false
        type: string
        default: "HEAD~1"

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog scan
        uses: trufflesecurity/trufflehog@v3
        with:
          extra_args: --only-verified --since-commit=${{ inputs.scan-since-commit }}
